# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2
project_name: lazyssh

before:
  hooks:
    - go mod verify

builds:
  - id: lazyssh
    main: ./cmd
    binary: lazyssh
    env:
      - CGO_ENABLED=0
      - GO386=softfloat
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
      - "386"
    ignore:
      - goos: darwin
        goarch: "386"
      - goos: windows
        goarch: "386"
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    ldflags:
      - >-
        -s -w
        -X main.version={{ .Version }}
        -X main.gitCommit={{ .Commit }}

archives:
  - formats:
      - tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        formats:
          - zip
    files:
      - LICENSE
      - README.md

checksum:
  name_template: checksums.txt

changelog:
  use: github-native

release:
  mode: keep-existing
  replace_existing_artifacts: true
  footer: >-

    ---

    Released by [GoReleaser](https://goreleaser.com/).
